name: Deploy

on:
  pull_request:
    branches:
      - 'master'
      - 'release*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pizza-ordering-system-backend"
          heroku_email: "gulshanraj116@gmail.com"
